name: CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php-version: ['8.3', '8.4']
      fail-fast: false
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@2.35.5
        with:
          php-version: ${{ matrix.php-version }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd
          coverage: pcov
          tools: composer:v2
      
      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      
      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction
      
      - name: Check coding style
        run: composer codestyle
      
      - name: Run PHPStan
        run: composer phpstan
      
      - name: Run tests with coverage
        run: composer test-coverage

      - name: Coverage Check
        uses: ericsizemore/phpunit-coverage-check-action@1.0.0
        with:
          clover_file: ./coverage/clover.xml
          threshold: 80
      
      - name: Generate coverage summary
        if: matrix.php-version == '8.3'
        run: |
          php -r "
          \$xml = simplexml_load_file('coverage/clover.xml');
          \$metrics = \$xml->project->metrics;
          \$statements = (int)\$metrics['statements'];
          \$coveredstatements = (int)\$metrics['coveredstatements'];
          \$coverage = \$statements > 0 ? round((\$coveredstatements / \$statements) * 100, 2) : 0;
          echo \"## Coverage Report\\n\";
          echo \"📊 **Total Coverage: {\$coverage}%**\\n\\n\";
          echo \"- Covered Statements: {\$coveredstatements}/{\$statements}\\n\";
          file_put_contents(getenv('GITHUB_STEP_SUMMARY'), \"## Coverage Report\\n📊 **Total Coverage: {\$coverage}%**\\n\\n- Covered Statements: {\$coveredstatements}/{\$statements}\\n\", FILE_APPEND);
          "
